# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\"\"\n\x06Vertex\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"#\n\x07\x42racket\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"%\n\x08Terminal\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"p\n\x04\x45\x64ge\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nvertex1_id\x18\x02 \x01(\t\x12\x12\n\nvertex2_id\x18\x03 \x01(\t\x12\x15\n\x0bterminal_id\x18\x04 \x01(\tH\x00\x12\x14\n\nbracket_id\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\"\x92\x01\n\x05Graph\x12\x19\n\x08vertices\x18\x01 \x03(\x0b\x32\x07.Vertex\x12\x14\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x05.Edge\x12\x0f\n\x07initial\x18\x03 \x01(\t\x12\r\n\x05\x66inal\x18\x04 \x03(\t\x12\x1c\n\tterminals\x18\x05 \x03(\x0b\x32\t.Terminal\x12\x1a\n\x08\x62rackets\x18\x06 \x03(\x0b\x32\x08.Bracketb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERTEX']._serialized_start=15
  _globals['_VERTEX']._serialized_end=49
  _globals['_BRACKET']._serialized_start=51
  _globals['_BRACKET']._serialized_end=86
  _globals['_TERMINAL']._serialized_start=88
  _globals['_TERMINAL']._serialized_end=125
  _globals['_EDGE']._serialized_start=127
  _globals['_EDGE']._serialized_end=239
  _globals['_GRAPH']._serialized_start=242
  _globals['_GRAPH']._serialized_end=388
# @@protoc_insertion_point(module_scope)
