# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grammar.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'grammar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrammar.proto\x12\x07grammar\x1a\x0c\x63ommon.proto\"@\n\x06Symbol\x12\x15\n\x0bterminal_id\x18\x01 \x01(\tH\x00\x12\x17\n\rneterminal_id\x18\x02 \x01(\tH\x00\x42\x06\n\x04kind\"/\n\x0b\x41lternative\x12 \n\x07symbols\x18\x01 \x03(\x0b\x32\x0f.grammar.Symbol\"9\n\x04Rule\x12\x0e\n\x06lhs_id\x18\x01 \x01(\t\x12!\n\x03rhs\x18\x02 \x03(\x0b\x32\x14.grammar.Alternative\"\x87\x01\n\x07Grammar\x12#\n\tterminals\x18\x01 \x03(\x0b\x32\x10.common.Terminal\x12\'\n\x0bneterminals\x18\x02 \x03(\x0b\x32\x12.common.Neterminal\x12\x1c\n\x05rules\x18\x03 \x03(\x0b\x32\r.grammar.Rule\x12\x10\n\x08start_id\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grammar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYMBOL']._serialized_start=40
  _globals['_SYMBOL']._serialized_end=104
  _globals['_ALTERNATIVE']._serialized_start=106
  _globals['_ALTERNATIVE']._serialized_end=153
  _globals['_RULE']._serialized_start=155
  _globals['_RULE']._serialized_end=212
  _globals['_GRAMMAR']._serialized_start=215
  _globals['_GRAMMAR']._serialized_end=350
# @@protoc_insertion_point(module_scope)
